# netlify.toml

[build]
  command = "pip install -r requirements.txt"
  publish = "public"

[functions]
  directory = "netlify"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
  force = true